Jfile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -28,7 +28,14 @@ node_version=$(node --version)
 # Check if the current Node.js version matches the expected version
 if [ "$node_version" != "v$EXPECTED_NODE_VERSION" ]
 then
-            nvm install ${EXPECTED_NODE_VERSION}
+          if ! command -v nvm &> /dev/null
+                    then
+                                            echo "nvm not found. Installing nvm..."
+                    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
+
+                    fi
+
+                                nvm install ${EXPECTED_NODE_VERSION}
             nvm use ${EXPECTED_NODE_VERSION}
 echo "Node of version $(node --version) installed"
             fi
