Jfile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -1,17 +1,29 @@
 pipeline {
  agent any
 
+environment{
+
+             PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
+}
  stages{
 
   stage('Install Dependencies'){
     steps{
          sh '''
-                    curl -o- -L https://yarnpkg.com/install.sh | bash
-                    export PATH=$HOME/.yarn/bin:$PATH
+          if ! command -v yarn &> /dev/null
+                    then
+                        echo "Yarn not found. Installing Yarn..."
+                        curl -o- -L https://yarnpkg.com/install.sh | bash
+                    else
+                        echo "Yarn is already installed"
+                    fi
+
+                    # Verify Yarn version
                     yarn --version
-                    yarn
                     '''
             echo "Yarn installed"
+            sh 'yarn'
+            echo "Node modules created"
   }
   }
   stage('Run Tests'){
